---
all:
  vars:
    ansible_user: cloud_user
    ssl_enable: true
      #ansible_become: true
zookeepers:
  hosts:
    kafka-1.internal:
      ansible_host: 35.179.132.134
      myid: 10
    kafka-2.internal:
      ansible_host: 3.8.8.124
      myid: 20
    kafka-3.internal:
      ansible_host: 3.10.116.124
      myid: 30

brokers:
  hosts:
    kafka-1.internal:
      ansible_host: 35.179.132.134
      myid: 10
    kafka-2.internal:
      ansible_host: 3.8.8.124
      myid: 20
    kafka-3.internal:
      ansible_host: 18.169.183.61
      myid: 30
