---
all:
  vars:
    ansible_user: cloud_user
    ssl_enable: true
      #ansible_become: true
zookeepers:
  hosts:
    kafka-1.internal:
      ansible_host: 18.171.237.242
      myid: 1
    kafka-2.internal:
      ansible_host: 18.170.37.208
      myid: 2
    kafka-3.internal:
      ansible_host: 3.8.39.137
      myid: 3

brokers:
  hosts:
    kafka-1.internal:
      ansible_host: 18.171.237.242
      myid: 1
    kafka-2.internal:
      ansible_host: 18.170.37.208
      myid: 2
    kafka-3.internal:
      ansible_host: 3.8.39.137
      myid: 3
