---
- hosts: brokers
  become: yes
  vars:
    confluent_version: "5.2"

  tasks:
    - name: Add the GNU Privacy Guard (GPG)
      ansible.builtin.apt_key:
        url: https://packages.confluent.io/deb/{{confluent_version}}/archive.key
        state: present
    - name: Add the package repository
      ansible.builtin.apt_repository:
         repo: "deb [arch=amd64] https://packages.confluent.io/deb/{{confluent_version}} stable main"
         state: present
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install java-8 package to have a java support then the confluent community package
      ansible.builtin.apt:
        name:
          - openjdk-8-jre-headless
          - confluent-community-2.12
        state: present

